var objects;
objects[0] = noone;
objects[1] = obj_cobbleblock;
objects[2] = obj_metalblock;
objects[3] = obj_powerup_minimize;
objects[4] = obj_powerup_maximize;
objects[5] = obj_boxblock;
objects[6] = obj_mill;
objects[7] = obj_mill_single;
objects[8] = obj_cannon;
return objects;
