var objects;
objects[0] = noone;
objects[1] = obj_cobbleblock;
objects[2] = obj_metalblock;
objects[3] = obj_powerup_minimize;
objects[4] = obj_powerup_maximize;
objects[5] = obj_boxblock;
objects[6] = obj_mill;
objects[7] = obj_mill_single;
objects[8] = obj_cannon;
objects[9] = obj_door;
objects[10] = obj_plant_enemy;
objects[11] = obj_crystal;
objects[12] = obj_slime;
objects[13] = obj_ghost;
objects[14] = obj_guardian;
return objects;
