var objects;
objects[0] = spr_cloud_soft1;
objects[1] = spr_cloud_soft2;
objects[2] = spr_cloud_soft3;
objects[3] = spr_cloud_soft4;
objects[4] = spr_cloud_soft5;
objects[5] = spr_cloud_soft6;
objects[6] = spr_cloud_streak1;
objects[7] = spr_cloud_streak2;
objects[8] = spr_cloud_streak3;
objects[9] = spr_cloud_streak4;
return objects;
