InitEnemy();
InitCollision();
slime_angle = 0;
image_speed = 0.5;
image_alpha = 0.9;
slime_angle = 45;
init_slime = false;
enemySpeed = 5;
timer = 0;
    jump_timer = global.time + random_range(1000000,5000000);
jump_direction[0] = 0;
jump_direction[1] = 0;
jump = false;
//show_debug_message(slime_angle);
movement_direction = 0;
